# PlatformIO pre-build hook: apply the LilyGoLib source patches this firmware
# depends on, after lib_deps are fetched. These live inside .pio/libdeps/ (which
# is gitignored and reset by `pio run -t clean` or any library refetch), so
# without this hook a fresh checkout builds incorrectly or fails to compile.
# Idempotent and runs every build.
#
# Patches:
#   * SEND_BUF_SIZE 16384 -> 4096 in LilyGoDispInterface.cpp
#       Stock 32 KB SPI/DMA chunks fail with ESP_ERR_NO_MEM once WiFi
#       promiscuous + active BLE scan (wardriver) eat most of internal SRAM,
#       so screen redraws partially fail (wardriver->clock appears to freeze).
#       8 KB chunks fit in the SRAM left over. See README.
#   * LV_USE_SNAPSHOT 0 -> 1 in lv_conf.h
#       Required by screenshot.cpp (lv_snapshot_take); LilyGoLib ships it off.
Import("env")  # noqa: F821 (provided by the PlatformIO build environment)
import os
import re
import subprocess

libdeps = env.subst("$PROJECT_LIBDEPS_DIR")
pioenv  = env.subst("$PIOENV")
src_dir = os.path.join(libdeps, pioenv, "LilyGoLib", "src")

# (filename, #define name, required value)
PATCHES = [
    ("LilyGoDispInterface.cpp", "SEND_BUF_SIZE",   "(4096)"),
    ("lv_conf.h",               "LV_USE_SNAPSHOT", "1"),
]


def set_define(path, name, value):
    if not os.path.isfile(path):
        print("[patch_lilygolib] WARNING: %s not found; %s NOT patched" % (path, name))
        return
    with open(path, "r", encoding="utf-8") as f:
        src = f.read()
    pat = re.compile(r"(#define\s+" + re.escape(name) + r"\s+)(\S+)")
    m = pat.search(src)
    if not m:
        print("[patch_lilygolib] WARNING: #define %s not found in %s" % (name, os.path.basename(path)))
        return
    if m.group(2) == value:
        print("[patch_lilygolib] %s already %s" % (name, value))
        return
    src = pat.sub(lambda mm: mm.group(1) + value, src, count=1)
    with open(path, "w", encoding="utf-8") as f:
        f.write(src)
    print("[patch_lilygolib] %s: %s -> %s" % (name, m.group(2), value))


for fname, name, value in PATCHES:
    set_define(os.path.join(src_dir, fname), name, value)


# Generate a build-only header rather than modifying tracked source. The
# semantic version identifies the release family; this revision identifies the
# exact source used for a binary and appends "-dirty" if it was built with
# uncommitted changes. FW_BUILD_ID can be supplied by archive/CI builds that do
# not have a .git directory.
project_dir = env.subst("$PROJECT_DIR")
generated_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")
generated_header = os.path.join(generated_dir, "firmware_build.h")


def git_text(*args):
    try:
        return subprocess.check_output(
            ["git", "-C", project_dir, *args],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return ""


build_id = os.environ.get("FW_BUILD_ID", "").strip()
if not build_id:
    build_id = git_text("rev-parse", "--short=8", "HEAD") or "source"
    if git_text("status", "--porcelain", "--untracked-files=normal"):
        build_id += "-dirty"

# Keep the generated value safe inside a C string literal even if a CI job
# supplies an unusual override.
build_id = re.sub(r"[^A-Za-z0-9._+-]", "_", build_id)[:40] or "source"
header = (
    "#pragma once\n"
    "// Generated by scripts/patch_lilygolib.py; do not edit.\n"
    '#define FW_BUILD_ID "%s"\n' % build_id
)
os.makedirs(generated_dir, exist_ok=True)
old_header = ""
if os.path.isfile(generated_header):
    with open(generated_header, "r", encoding="utf-8") as f:
        old_header = f.read()
if old_header != header:
    with open(generated_header, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
env.Append(CPPPATH=[generated_dir])
print("[firmware_version] build %s" % build_id)
